[tool.poetry]
name = "catasto-ingest"
version = "0.1.0"
description = "Catasto workflow for the automatic ingestion from Smidt"
authors = ["Francesco Bartoli <francesco.bartoli@geobeyond.it>"]
license = "MIT"
packages = [
    {include = "flows", from = "."},
    # {include = "smidt", from = "libs/src/smidt/"},
    # {include = "smidt/**/*.py", from = "libs/src/smidt/"},
]

[tool.poetry.dependencies]
python = "^3.10"
prefect = {extras = ["aws","docker"], version = "<3.0"}
pyfiglet = "^0.8.post1"
sister = {path = "libs/src/sister/", develop = false}
smidt = {path = "libs/src/smidt/", develop = false}
catasto = {path = "libs/src/catasto/", develop = false}
s3fs = "^2023.12.2"
mkdocs = "^1.5.3"
mkdocs-material = "^9.5.39"
termynal = "^0.11.1"
minio = "^7.2.14"

[tool.poetry.group.dev.dependencies]
ipython = "^8.20.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
